"""Add password attribute to User model

Revision ID: 54077ff72b7e
Revises: 
Create Date: 2023-03-13 21:27:49.851517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54077ff72b7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index('ix_task_timestamp')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('priority')
        batch_op.drop_column('description')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=280), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.create_index('ix_task_timestamp', ['timestamp'], unique=False)

    # ### end Alembic commands ###
